# Generated by Django 3.0.7 on 2020-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageitem',
            name='isbot',
            field=models.BooleanField(default=False),
        ),
    ]
